### PR TITLE
correct hale

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by chrzyki** [comment]
Thanks! CLDF folder seems to be missing from the PR? And why the decrease in concepts?

**Comment by LinguList** [comment]
I'd like you to run the cldf, as you have this all fixed on the same machine, for pyclics.
Decrease in concepts is due to mergers, I assume, as the data contains the same concept in different places, which were, I think, however, not handled correctly before. What is essential is that I tackled the problem of the mismatch between the concepticon list with the stedt representation manually and explicitly, by adding all mismatches to the file raw/srcid.tsv.

**Comment by chrzyki** [comment]
Yup, that's nice. Thanks! I've re-generated the CLDF and pushed into this PR. Please don't merge for new as I'd like to test something.

**Comment by chrzyki** [comment]
Good, just wanted to see whether Travis picks up the failing tests. Updating tests now and then merge?

**Comment by LinguList** [comment]
yes!

**Pull request merged**
